/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialitesRouteImport } from './routes/specialites'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as PraticiensRouteImport } from './routes/praticiens'
import { Route as LeCentreRouteImport } from './routes/le-centre'
import { Route as InformationsPratiquesRouteImport } from './routes/informations-pratiques'
import { Route as IndexRouteImport } from './routes/index'

const SpecialitesRoute = SpecialitesRouteImport.update({
  id: '/specialites',
  path: '/specialites',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticiensRoute = PraticiensRouteImport.update({
  id: '/praticiens',
  path: '/praticiens',
  getParentRoute: () => rootRouteImport,
} as any)
const LeCentreRoute = LeCentreRouteImport.update({
  id: '/le-centre',
  path: '/le-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationsPratiquesRoute = InformationsPratiquesRouteImport.update({
  id: '/informations-pratiques',
  path: '/informations-pratiques',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/informations-pratiques': typeof InformationsPratiquesRoute
  '/le-centre': typeof LeCentreRoute
  '/praticiens': typeof PraticiensRoute
  '/rendez-vous': typeof RendezVousRoute
  '/specialites': typeof SpecialitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/informations-pratiques': typeof InformationsPratiquesRoute
  '/le-centre': typeof LeCentreRoute
  '/praticiens': typeof PraticiensRoute
  '/rendez-vous': typeof RendezVousRoute
  '/specialites': typeof SpecialitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/informations-pratiques': typeof InformationsPratiquesRoute
  '/le-centre': typeof LeCentreRoute
  '/praticiens': typeof PraticiensRoute
  '/rendez-vous': typeof RendezVousRoute
  '/specialites': typeof SpecialitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/informations-pratiques'
    | '/le-centre'
    | '/praticiens'
    | '/rendez-vous'
    | '/specialites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/informations-pratiques'
    | '/le-centre'
    | '/praticiens'
    | '/rendez-vous'
    | '/specialites'
  id:
    | '__root__'
    | '/'
    | '/informations-pratiques'
    | '/le-centre'
    | '/praticiens'
    | '/rendez-vous'
    | '/specialites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InformationsPratiquesRoute: typeof InformationsPratiquesRoute
  LeCentreRoute: typeof LeCentreRoute
  PraticiensRoute: typeof PraticiensRoute
  RendezVousRoute: typeof RendezVousRoute
  SpecialitesRoute: typeof SpecialitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialites': {
      id: '/specialites'
      path: '/specialites'
      fullPath: '/specialites'
      preLoaderRoute: typeof SpecialitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticiens': {
      id: '/praticiens'
      path: '/praticiens'
      fullPath: '/praticiens'
      preLoaderRoute: typeof PraticiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-centre': {
      id: '/le-centre'
      path: '/le-centre'
      fullPath: '/le-centre'
      preLoaderRoute: typeof LeCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informations-pratiques': {
      id: '/informations-pratiques'
      path: '/informations-pratiques'
      fullPath: '/informations-pratiques'
      preLoaderRoute: typeof InformationsPratiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InformationsPratiquesRoute: InformationsPratiquesRoute,
  LeCentreRoute: LeCentreRoute,
  PraticiensRoute: PraticiensRoute,
  RendezVousRoute: RendezVousRoute,
  SpecialitesRoute: SpecialitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
